"""initial schema

Revision ID: 11156b49a0eb
Revises: 
Create Date: 2026-06-15 17:02:07.384807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11156b49a0eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_vehicle_id'), 'missions', ['vehicle_id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_codes', sa.JSON(), nullable=False),
    sa.Column('zone_entered', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_vehicle_id'), 'telemetry_events', ['vehicle_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('speed_mps', sa.Float(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('zones',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('telemetry_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['telemetry_event_id'], ['telemetry_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_vehicle_id_detected_at', 'anomalies', ['vehicle_id', 'detected_at'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_vehicle_id'), 'maintenance_records', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_vehicle_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index('ix_anomalies_vehicle_id_detected_at', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('zones')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_telemetry_events_vehicle_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_missions_vehicle_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
